[package]
name = "dlloader"
version = "0.2.1"
edition = "2024"
authors = ["Gleb Petrikov"]
license = "MIT OR Apache-2.0"
description = "A cross-platform dynamic library loader"
readme = "README.md"
repository = "https://github.com/glpetrikov/dlloader"
documentation = "https://docs.rs/dlloader"
keywords = ["dynamic-loading", "dll", "so", "dylib", "loader"]
categories = ["api-bindings", "development-tools::ffi"]

[dependencies]
dlopen2 = "0.9.0"
tempfile = "3.27.0"
thiserror = "2.0.20"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[workspace]
members = ["dlloader-fixture"]
